//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Action()
        {
            this.Action1 = new HashSet<Action>();
            this.Action_Tache = new HashSet<Action_Tache>();
            this.Detection = new HashSet<Detection>();
            this.Salarie_Action = new HashSet<Salarie_Action>();
            this.Verification1 = new HashSet<Verification>();
            this.Reglementation = new HashSet<Reglementation>();
        }
    
        public int idAction { get; set; }
        public Nullable<System.DateTime> dateDebut { get; set; }
        public Nullable<double> delais { get; set; }
        public Nullable<double> acheve { get; set; }
        public Nullable<int> numeroImportance { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public string pieceJustificative { get; set; }
        public string nom { get; set; }
        public string recurrence { get; set; }
        public Nullable<int> idFamille { get; set; }
        public Nullable<int> idVerification { get; set; }
        public Nullable<int> idSite { get; set; }
        public Nullable<int> idAction_1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action> Action1 { get; set; }
        public virtual Action Action2 { get; set; }
        public virtual Famille Famille { get; set; }
        public virtual Site Site { get; set; }
        public virtual Verification Verification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Action_Tache> Action_Tache { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detection> Detection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salarie_Action> Salarie_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verification> Verification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reglementation> Reglementation { get; set; }
    }
}
