//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action_Tache
    {
        public string detail { get; set; }
        public Nullable<bool> fait { get; set; }
        public int idTache { get; set; }
        public int idAction { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Tache Tache { get; set; }
    }
}
