//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LapyrEntities : DbContext
    {
        public LapyrEntities()
            : base("name=LapyrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action_Tache> Action_Tache { get; set; }
        public virtual DbSet<ActionQSE> ActionQSEs { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<Detection> Detections { get; set; }
        public virtual DbSet<Famille> Familles { get; set; }
        public virtual DbSet<QSE> QSEs { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Reglementation> Reglementations { get; set; }
        public virtual DbSet<Salarie_Action> Salarie_Action { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Tache> Taches { get; set; }
        public virtual DbSet<Verification> Verifications { get; set; }
    }
}
