//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lapyrEntities : DbContext
    {
        public lapyrEntities()
            : base("name=lapyrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Action_Tache> Action_Tache { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Detection> Detection { get; set; }
        public virtual DbSet<Famille> Famille { get; set; }
        public virtual DbSet<QSE> QSE { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Reglementation> Reglementation { get; set; }
        public virtual DbSet<Salarie_Action> Salarie_Action { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<Tache> Tache { get; set; }
        public virtual DbSet<Verification> Verification { get; set; }
    }
}
