//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detection
    {
        public int idDetection { get; set; }
        public string nomDetection { get; set; }
        public string detailDetection { get; set; }
        public string descriptionAnalyse { get; set; }
        public string conclusionAnalyse { get; set; }
        public Nullable<int> idAction { get; set; }
    
        public virtual ActionQSE ActionQSE { get; set; }
    }
}
