//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QSE()
        {
            this.Salarie_Action = new HashSet<Salarie_Action>();
        }
    
        public int idSalarie { get; set; }
        public string nom { get; set; }
        public string statutHierarchique { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string prenom { get; set; }
        public string identifiant { get; set; }
        public string mdp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salarie_Action> Salarie_Action { get; set; }
    }
}
