//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaPyrenenne.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarie_Action
    {
        public string type { get; set; }
        public int idSalarie { get; set; }
        public int idAction { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual QSE QSE { get; set; }
    }
}
